name: 'Submodules Staging-1'

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@master

    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Commit update
      run: |
        git config --global user.name 'Sanjana-ks'
        git config --global user.email 'sanjana.gharewal@ksolves.com'
        git remote set-url origin https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule" 
        git push || echo "No changes to commit"
